"""Mission-independent spectral wave-candidate analysis.

The core accepts NumPy arrays in ``(time, frequency)`` orientation.  Mission
packages provide instrument presets, quality masks, and dataset adapters.
"""

from sopran.experimental.waves.clustering import (
    ALGORITHM_VERSION as CLUSTERING_ALGORITHM_VERSION,
)
from sopran.experimental.waves.clustering import (
    BackgroundResidualClusteringConfig,
    BackgroundResidualClusteringResult,
    ClusterAssignments,
    MissingValueMetadata,
    PcaMetadata,
    ResidualTrimMetadata,
    ScalerMetadata,
    clustering_config_hash,
    fit_background_residual_clustering,
)
from sopran.experimental.waves.detector import (
    BBN_ESW_CANDIDATE,
    FPE_LOW_RIDGE_CANDIDATE,
    INSTRUMENT_RFI_CANDIDATE,
    PLASMA_LINE_RIDGE_CANDIDATE,
    RADIO_AKR_CANDIDATE,
    TRACKED_HIGH_PLASMA_RIDGE_CANDIDATE,
    TRACKED_LOW_FPE_RIDGE_CANDIDATE,
    WAVE_CANDIDATE_PHENOMENA,
    detect_wave_candidates,
)
from sopran.experimental.waves.intervals import (
    build_candidate_intervals,
    merge_half_open_intervals,
    stable_detector_run_id,
    stable_interval_id,
    stable_window_id,
)
from sopran.experimental.waves.model import (
    CandidateInterval,
    FixedLine,
    FrequencyBand,
    InputScale,
    LineDetectionRule,
    LineFeatures,
    PeakFeatures,
    PeakRule,
    RidgeTrack,
    RidgeTrackerConfig,
    WaveDetectionResult,
    WaveDetectorConfig,
    WaveFeatureSet,
    WindowAnchor,
    WindowConfig,
    WindowedSpectra,
    detector_config_id,
    feature_spec,
    feature_spec_hash,
    feature_spec_id,
    frequency_to_density_cm3,
    frequency_to_required_b_nt,
)
from sopran.experimental.waves.ridge import (
    frequency_local_contrast,
    track_spectral_ridge,
    viterbi_ridge_track,
)
from sopran.experimental.waves.spectral import (
    extract_wave_features,
    fixed_line_keep_mask,
    interpolate_log_spectrum,
    local_peak_features,
    log_frequency_grid,
    normalize_window_spectra,
    power_to_db,
    prepare_windowed_spectra,
    robust_center_scale,
    time_to_seconds,
)

__all__ = [
    "BBN_ESW_CANDIDATE",
    "FPE_LOW_RIDGE_CANDIDATE",
    "INSTRUMENT_RFI_CANDIDATE",
    "PLASMA_LINE_RIDGE_CANDIDATE",
    "RADIO_AKR_CANDIDATE",
    "TRACKED_HIGH_PLASMA_RIDGE_CANDIDATE",
    "TRACKED_LOW_FPE_RIDGE_CANDIDATE",
    "WAVE_CANDIDATE_PHENOMENA",
    "BackgroundResidualClusteringConfig",
    "BackgroundResidualClusteringResult",
    "CLUSTERING_ALGORITHM_VERSION",
    "CandidateInterval",
    "ClusterAssignments",
    "FixedLine",
    "FrequencyBand",
    "InputScale",
    "LineDetectionRule",
    "LineFeatures",
    "MissingValueMetadata",
    "PcaMetadata",
    "PeakFeatures",
    "PeakRule",
    "RidgeTrack",
    "RidgeTrackerConfig",
    "ResidualTrimMetadata",
    "ScalerMetadata",
    "WaveDetectionResult",
    "WaveDetectorConfig",
    "WaveFeatureSet",
    "WindowAnchor",
    "WindowConfig",
    "WindowedSpectra",
    "build_candidate_intervals",
    "clustering_config_hash",
    "detect_wave_candidates",
    "detector_config_id",
    "extract_wave_features",
    "feature_spec",
    "feature_spec_hash",
    "feature_spec_id",
    "fixed_line_keep_mask",
    "fit_background_residual_clustering",
    "frequency_local_contrast",
    "frequency_to_density_cm3",
    "frequency_to_required_b_nt",
    "interpolate_log_spectrum",
    "local_peak_features",
    "log_frequency_grid",
    "merge_half_open_intervals",
    "normalize_window_spectra",
    "power_to_db",
    "prepare_windowed_spectra",
    "robust_center_scale",
    "stable_detector_run_id",
    "stable_interval_id",
    "stable_window_id",
    "time_to_seconds",
    "track_spectral_ridge",
    "viterbi_ridge_track",
]
