"""Robust electron-reflectometry effective-field estimation."""

from sopran.analysis.electron_reflection.beam_diagnostics import (
    GlobalJointBeamDecomposition,
    decompose_global_joint_beam,
    plot_global_joint_beam_decomposition,
)
from sopran.analysis.electron_reflection.binary_surface import (
    BinaryLossConeEstimate,
    BinaryLossConeFitSettings,
    BinaryLossConeModelFit,
    fit_binary_loss_cone,
)
from sopran.analysis.electron_reflection.global_joint import (
    BackgroundModel,
    EdgeTransition,
    GlobalFullFOV,
    GlobalJointEstimate,
    GlobalJointFitSettings,
    GlobalJointModelFit,
    GlobalNormalizedFlux,
    GlobalPitchCountObservation,
    GlobalSensorFit,
    LossConeModel,
    PitchOrientation,
    ResolvedEdgeTransition,
    SecondaryBeamMode,
    fit_global_joint_effective_field,
    plot_global_joint_circular_pitch_view,
    plot_global_joint_effective_field_fit,
)
from sopran.analysis.electron_reflection.halekas import (
    HalekasDistributionFit,
    HalekasEdgeTransition,
    HalekasFitSettings,
    fit_halekas_distribution,
)
from sopran.analysis.electron_reflection.joint import (
    JointEffectiveFieldEstimate,
    JointEffectiveFieldModelFit,
    JointObservationFit,
    fit_joint_effective_field,
    plot_joint_effective_field_fit,
)
from sopran.analysis.electron_reflection.model import (
    ContrastModel,
    EffectiveFieldDiagnostics,
    EffectiveFieldEstimate,
    EffectiveFieldFitSettings,
    EffectiveFieldModelFit,
    EffectiveFieldQualitySettings,
    ElectronReflectionCounts,
    FitQualityGrade,
    fit_effective_field,
    mirror_boundary_sin2,
    mirror_transmission_probability,
    simulate_electron_reflection_counts,
)

__all__ = [
    "BackgroundModel",
    "LossConeModel",
    "BinaryLossConeEstimate",
    "BinaryLossConeFitSettings",
    "BinaryLossConeModelFit",
    "ContrastModel",
    "EffectiveFieldDiagnostics",
    "EffectiveFieldEstimate",
    "EffectiveFieldFitSettings",
    "EffectiveFieldModelFit",
    "EffectiveFieldQualitySettings",
    "EdgeTransition",
    "ElectronReflectionCounts",
    "FitQualityGrade",
    "GlobalFullFOV",
    "GlobalJointBeamDecomposition",
    "GlobalJointEstimate",
    "GlobalJointFitSettings",
    "GlobalJointModelFit",
    "GlobalNormalizedFlux",
    "GlobalPitchCountObservation",
    "GlobalSensorFit",
    "HalekasDistributionFit",
    "HalekasEdgeTransition",
    "HalekasFitSettings",
    "JointEffectiveFieldEstimate",
    "JointEffectiveFieldModelFit",
    "JointObservationFit",
    "PitchOrientation",
    "ResolvedEdgeTransition",
    "SecondaryBeamMode",
    "decompose_global_joint_beam",
    "fit_binary_loss_cone",
    "fit_effective_field",
    "fit_global_joint_effective_field",
    "fit_halekas_distribution",
    "fit_joint_effective_field",
    "mirror_boundary_sin2",
    "mirror_transmission_probability",
    "plot_global_joint_circular_pitch_view",
    "plot_global_joint_beam_decomposition",
    "plot_joint_effective_field_fit",
    "plot_global_joint_effective_field_fit",
    "simulate_electron_reflection_counts",
]
